spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  type-aliases-package: com.order.model
  mapper-locations: classpath:mappers/*.xml

#mapper
#mappers 多个接口时逗号隔开
mapper:
  mappers: com.order.util.MyMapper
  not-empty: false
  identity: MYSQL

#pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

page: 5

test: orderServer
